config/routes.rb
Rails.application.routes.draw do
  root 'billboards#index'

  resources :billboards do
    resources :songs
  end
  
  resources :artists do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard, optional: true
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :update, :edit, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :update, :edit, :destroy]

  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @billboard = Billboard.new(billboard_params)

    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to @billboard
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private

    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

    def billboard_params
      params.require(:billboard).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @song = @artist.songs.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @song = @artist.songs.new(song_params)

    if @song.save
      redirect_to [@artist, @song]
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to [@artist, @song]
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_songs_path(@artist)
  end

  private
    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:name, :body)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<hr />
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form", artist: @artist %>

<%= link_to "Show", artist_path(@artist) %> |
<%= link_to "Back", artists_path %>

app/views/artists/index.html.erb
<h1>Click An Artist To View Songs</h1>
<%= link_to 'Create a new Artist', new_artist_path %>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist %></li>
  <% end %>
</ul>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<hr />
<p>What would you lke to do?</p>
<%= link_to 'View Artists', artists_path %>
<br />
<%= link_to 'Edit Artist', edit_artist_path(@artist) %>
<br />
<%= button_to 'Delete Artist', @artist, method: :delete %>
<br />
<%= link_to 'Show Songs', artist_songs_path(@artist) %>
<br />
<%= link_to 'Show Billboards', billboards_path %>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? 'Edit Billboard' : 'Create Billboard' %></h1>
<hr />
<%= form_for @billboard do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Edit Billboard</h1>

<%= render "form", billboard: @billboard %>

<%= link_to "Show", billboard_path(@billboard) %> |
<%= link_to "Back", billboards_path %>

app/views/billboards/index.html.erb
<h1>Click A Billboard To View Songs</h1>
<%= link_to 'Create a new Billboard', new_billboard_path %>
<ul>
  <% @billboards.each do |billboard| %>
    <li><%= link_to billboard.name, billboard %></li>
  <% end %>
</ul>

app/views/billboards/show.html.erb
<h1><%= @billboard.name %></h1>
<hr />
<p>What would you lke to do?</p>
<%= link_to 'View Billboards', billboards_path %>
<br />
<%= link_to 'Edit Billboard', edit_billboard_path(@billboard) %>
<br />
<%= button_to 'Delete Billboard', @billboard, method: :delete %>
<br />
<%= link_to 'Show Songs', billboard_songs_path(@billboard) %>
<br />
<%= link_to 'Show Artists', artists_path %>
<%# For whatever reason I can't get to songs from here, I'm not sure exactly why that is. %>
<%# I have been trying to look up this code and figure it out, but have been unsucessful at it. %>
<%# ActiveRecord::RecordNotFound in SongsController#index is the error I keep getting and I cant figure out why. %>
<%# I was also unable to get the songs showing up on the billboard unfortuantly. %>
<%# If you could possibly point me in the right direction of where to look so that I can get this figured out I would appriciate it. %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%# javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit Song' : 'Create Song' %></h1>
<hr />
<%=  form_for [@artist, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render "form", song: @song %>

<%= link_to "Show", song_path(@song) %> |
<%= link_to "Back", songs_path %>

app/views/songs/index.html.erb
<h1>Click A Song To View</h1>
<%= link_to 'Create a new song', new_artist_song_path(@artist) %>
<ul>
  <% @songs.each do |song| %>
    <li><%= link_to song.name, [@artist,song] %></li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/songs/show.html.erb
<h1><%= @artist.name %> - <%= @song.name %></h1>

<%= link_to 'Edit Song', edit_artist_song_path([@artist, @song]) %>
<%= button_to 'Delete Song', [@artist, @song], method: :delete %>
<%= link_to 'Back to Songs', artist_songs_path(@artist) %>
<br />
<%= link_to 'Show Billboards', billboards_path %>
<br />
<%= link_to 'Show Artists', artists_path %>